/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/beta/testkits/enzyme-typescript.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
import { BaseUniDriver } from 'wix-ui-test-utils/base-driver';
import { BaseDriver } from 'wix-ui-test-utils/driver-factory';
import { ReactWrapper } from 'enzyme';

import { PopoverMenuDriver } from '../../src/beta/PopoverMenu/PopoverMenu.uni.driver';

declare namespace EnzymeTestkit {
  type EnzymeUniTestkitFactory<T> = (params: {
    wrapper: ReactWrapper;
    dataHook: string;
  }) => T;

  export const PopoverMenuTestkit: EnzymeUniTestkitFactory<PopoverMenuDriver>;

}

export = EnzymeTestkit;
