/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/beta/testkits/vanilla-typescript.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
import { BaseUniDriver } from 'wix-ui-test-utils/base-driver';
import { BaseDriver } from 'wix-ui-test-utils/driver-factory';

import { PopoverMenuDriver } from '../../src/beta/PopoverMenu/PopoverMenu.uni.driver';

declare namespace VanillaTestkit {
  type VanillaUniTestkitFactory<T> = (params: {
    wrapper: HTMLElement;
    dataHook: string;
  }) => T;

  export const PopoverMenuTestkit: VanillaUniTestkitFactory<PopoverMenuDriver>;

}

export = VanillaTestkit;
