/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/beta/testkits/puppeteer.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
import 'regenerator-runtime/runtime';
import { puppeteerUniTestkitFactoryCreator } from 'wix-ui-test-utils/puppeteer';

import { PopoverMenuDriver } from '../../src/beta/PopoverMenu/PopoverMenu.uni.driver';

export const PopoverMenuTestkit = puppeteerUniTestkitFactoryCreator(
  PopoverMenuDriver,
);
