/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/testkits/protractor.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
import 'regenerator-runtime/runtime';
import {
  protractorTestkitFactoryCreator,
  protractorUniTestkitFactoryCreator,
} from 'wix-ui-test-utils/protractor';

// here for historical reasons, should probably deprecate it
export {
  waitForVisibilityOf,
  scrollToElement,
} from 'wix-ui-test-utils/protractor';

import tooltipDriverFactory from '../src/Tooltip/Tooltip.protractor.driver';
import { tooltipDriverFactory as tooltipNextDriverFactory } from '../src/Tooltip/TooltipNext/Tooltip.uni.driver';

export const tooltipTestkitFactory = protractorTestkitFactoryCreator(
  tooltipDriverFactory,
);

export const TooltipTestkit = protractorUniTestkitFactoryCreator(
  tooltipNextDriverFactory,
);

import { accordionDriverFactory } from '../src/Accordion/Accordion.uni.driver';

export const accordionTestkitFactory = protractorUniTestkitFactoryCreator(
  accordionDriverFactory,
);

import addItemDriverFactory from '../src/AddItem/AddItem.protractor.driver';

export const addItemTestkitFactory = protractorTestkitFactoryCreator(
  addItemDriverFactory,
);

import autoCompleteDriverFactory from '../src/AutoComplete/AutoComplete.protractor.driver';

export const autoCompleteTestkitFactory = protractorTestkitFactoryCreator(
  autoCompleteDriverFactory,
);

import autoCompleteCompositeDriverFactory from '../src/AutoCompleteComposite/AutoCompleteComposite.protractor.driver';

export const autoCompleteCompositeTestkitFactory = protractorTestkitFactoryCreator(
  autoCompleteCompositeDriverFactory,
);

import avatarDriverFactory from '../src/Avatar/Avatar.uni.driver';

export const avatarTestkitFactory = protractorUniTestkitFactoryCreator(
  avatarDriverFactory,
);

import badgeDriverFactory from '../src/Badge/Badge.protractor.driver';

export const badgeTestkitFactory = protractorTestkitFactoryCreator(
  badgeDriverFactory,
);

import badgeSelectDriverFactory from '../src/BadgeSelect/BadgeSelect.protractor.driver';

export const badgeSelectTestkitFactory = protractorTestkitFactoryCreator(
  badgeSelectDriverFactory,
);

import { boxDriverFactory } from '../src/Box/Box.uni.driver';

export const boxTestkitFactory = protractorUniTestkitFactoryCreator(
  boxDriverFactory,
);

import breadcrumbsDriverFactory from '../src/Breadcrumbs/Breadcrumbs.protractor.driver';

export const breadcrumbsTestkitFactory = protractorTestkitFactoryCreator(
  breadcrumbsDriverFactory,
);

import { buttonDriverFactory } from '../src/Button/Button.uni.driver';

export const buttonTestkitFactory = protractorUniTestkitFactoryCreator(
  buttonDriverFactory,
);

import calendarDriverFactory from '../src/Calendar/Calendar.protractor.driver';

export const calendarTestkitFactory = protractorTestkitFactoryCreator(
  calendarDriverFactory,
);

import calendarPanelDriverFactory from '../src/CalendarPanel/CalendarPanel.protractor.driver';

export const calendarPanelTestkitFactory = protractorTestkitFactoryCreator(
  calendarPanelDriverFactory,
);

import { calendarPanelFooterDriverFactory } from '../src/CalendarPanelFooter/CalendarPanelFooter.uni.driver';

export const calendarPanelFooterTestkitFactory = protractorUniTestkitFactoryCreator(
  calendarPanelFooterDriverFactory,
);

import cardGalleryItemDriverFactory from '../src/CardGalleryItem/CardGalleryItem.uni.driver';

export const cardGalleryItemTestkitFactory = protractorUniTestkitFactoryCreator(
  cardGalleryItemDriverFactory,
);

import carouselDriverFactory from '../src/Carousel/Carousel.protractor.driver';

export const carouselTestkitFactory = protractorTestkitFactoryCreator(
  carouselDriverFactory,
);

import checkboxDriverFactory from '../src/Checkbox/Checkbox.protractor.driver';

export const checkboxTestkitFactory = protractorTestkitFactoryCreator(
  checkboxDriverFactory,
);

import circularProgressBarDriverFactory from '../src/CircularProgressBar/CircularProgressBar.protractor.driver';

export const circularProgressBarTestkitFactory = protractorTestkitFactoryCreator(
  circularProgressBarDriverFactory,
);

import { closeButtonDriverFactory } from '../src/CloseButton/CloseButton.uni.driver';

export const closeButtonTestkitFactory = protractorUniTestkitFactoryCreator(
  closeButtonDriverFactory,
);

import { colorInputDriverFactory } from '../src/ColorInput/ColorInput.uni.driver';

export const colorInputTestkitFactory = protractorUniTestkitFactoryCreator(
  colorInputDriverFactory,
);

import colorPickerDriverFactory from '../src/ColorPicker/ColorPicker.protractor.driver';

export const colorPickerTestkitFactory = protractorTestkitFactoryCreator(
  colorPickerDriverFactory,
);

import { contactItemBuilderUniDriverFactory } from '../src/ContactItemBuilder/ContactItemBuilder.uni.driver';

export const contactItemBuilderTestkitFactory = protractorTestkitFactoryCreator(
  contactItemBuilderUniDriverFactory,
);

import counterBadgeDriverFactory from '../src/CounterBadge/CounterBadge.protractor.driver';

export const counterBadgeTestkitFactory = protractorTestkitFactoryCreator(
  counterBadgeDriverFactory,
);

import dataTableDriverFactory from '../src/DataTable/DataTable.protractor.driver';

export const dataTableTestkitFactory = protractorTestkitFactoryCreator(
  dataTableDriverFactory,
);

import { dateInputDriverFactory } from '../src/DateInput/DateInput.uni.driver';

export const dateInputTestkitFactory = protractorUniTestkitFactoryCreator(
  dateInputDriverFactory,
);

import datePickerDriverFactory from '../src/DatePicker/DatePicker.protractor.driver';

export const datePickerTestkitFactory = protractorTestkitFactoryCreator(
  datePickerDriverFactory,
);

import dropdownDriverFactory from '../src/Dropdown/Dropdown.protractor.driver';

export const dropdownTestkitFactory = protractorTestkitFactoryCreator(
  dropdownDriverFactory,
);

import { dropdownBaseDriverFactory } from '../src/DropdownBase/DropdownBase.uni.driver';

export const dropdownBaseTestkitFactory = protractorUniTestkitFactoryCreator(
  dropdownBaseDriverFactory,
);

import dropdownLayoutDriverFactory from '../src/DropdownLayout/DropdownLayout.protractor.driver';

export const dropdownLayoutTestkitFactory = protractorTestkitFactoryCreator(
  dropdownLayoutDriverFactory,
);

import editableSelectorDriverFactory from '../src/EditableSelector/EditableSelector.protractor.driver';

export const editableSelectorTestkitFactory = protractorTestkitFactoryCreator(
  editableSelectorDriverFactory,
);

import { editableTitleUniDriverFactory } from '../src/EditableTitle/EditableTitle.uni.driver';

export const editableTitleTestkitFactory = protractorUniTestkitFactoryCreator(
  editableTitleUniDriverFactory,
);

import emptyStateDriverFactory from '../src/EmptyState/EmptyState.protractor.driver';

export const emptyStateTestkitFactory = protractorTestkitFactoryCreator(
  emptyStateDriverFactory,
);

import { errorIndicatorDriverFactory } from '../src/ErrorIndicator/ErrorIndicator.uni.driver';

export const errorIndicatorTestkitFactory = protractorUniTestkitFactoryCreator(
  errorIndicatorDriverFactory,
);

import filePickerDriverFactory from '../src/FilePicker/FilePicker.protractor.driver';

export const filePickerTestkitFactory = protractorTestkitFactoryCreator(
  filePickerDriverFactory,
);

import floatingHelperDriverFactory from '../src/FloatingHelper/FloatingHelper.protractor.driver';

export const floatingHelperTestkitFactory = protractorTestkitFactoryCreator(
  floatingHelperDriverFactory,
);

import { floatingNotificationDriverFactory } from '../src/FloatingNotification/FloatingNotification.uni.driver';

export const floatingNotificationTestkitFactory = protractorUniTestkitFactoryCreator(
  floatingNotificationDriverFactory,
);

import formFieldDriverFactory from '../src/FormField/FormField.protractor.driver';

export const formFieldTestkitFactory = protractorTestkitFactoryCreator(
  formFieldDriverFactory,
);

import genericModalLayoutDriverFactory from '../src/GenericModalLayout/GenericModalLayout.protractor.driver';

export const genericModalLayoutTestkitFactory = protractorTestkitFactoryCreator(
  genericModalLayoutDriverFactory,
);

import googleAddressInputWithLabelDriverFactory from '../src/GoogleAddressInputWithLabel/GoogleAddressInputWithLabel.protractor.driver';

export const googleAddressWithInputTestkitFactory = protractorTestkitFactoryCreator(
  googleAddressInputWithLabelDriverFactory,
);

import { googlePreviewDriverFactory } from '../src/GooglePreview/GooglePreview.uni.driver';

export const googlePreviewTestkitFactory = protractorUniTestkitFactoryCreator(
  googlePreviewDriverFactory,
);

import headingDriverFactory from '../src/Heading/Heading.protractor.driver';

export const headingTestkitFactory = protractorTestkitFactoryCreator(
  headingDriverFactory,
);

import highlighterDriverFactory from '../src/Highlighter/Highlighter.protractor.driver';

export const highlighterTestkitFactory = protractorTestkitFactoryCreator(
  highlighterDriverFactory,
);

import { iconButtonDriverFactory } from '../src/IconButton/IconButton.uni.driver';

export const iconButtonTestkitFactory = protractorUniTestkitFactoryCreator(
  iconButtonDriverFactory,
);

import { toggleButtonDriverFactory } from '../src/ToggleButton/ToggleButton.uni.driver';

export const toggleButtonTestkitFactory = protractorUniTestkitFactoryCreator(
  toggleButtonDriverFactory,
);

import imageViewerDriverFactory from '../src/ImageViewer/ImageViewer.protractor.driver';

export const imageViewerTestkitFactory = protractorTestkitFactoryCreator(
  imageViewerDriverFactory,
);

import inputDriverFactory from '../src/Input/Input.protractor.driver';

export const inputTestkitFactory = protractorTestkitFactoryCreator(
  inputDriverFactory,
);

import inputAreaDriverFactory from '../src/InputArea/InputArea.protractor.driver';

export const inputAreaTestkitFactory = protractorTestkitFactoryCreator(
  inputAreaDriverFactory,
);

import inputWithOptionsDriverFactory from '../src/InputWithOptions/InputWithOptions.protractor.driver';

export const inputWithOptionsTestkitFactory = protractorTestkitFactoryCreator(
  inputWithOptionsDriverFactory,
);

import labelDriverFactory from '../src/Label/Label.protractor.driver';

export const labelTestkitFactory = protractorTestkitFactoryCreator(
  labelDriverFactory,
);

import { linearProgressBarDriverFactory } from '../src/LinearProgressBar/LinearProgressBar.protractor.driver';

export const linearProgressBarTestkitFactory = protractorTestkitFactoryCreator(
  linearProgressBarDriverFactory,
);

import { ListItemActionDriverFactory } from '../src/ListItemAction/ListItemAction.uni.driver';

export const ListItemActionTestkitFactory = protractorUniTestkitFactoryCreator(
  ListItemActionDriverFactory,
);

import loaderDriverFactory from '../src/Loader/Loader.protractor.driver';

export const loaderTestkitFactory = protractorTestkitFactoryCreator(
  loaderDriverFactory,
);

import { modalUniDriverFactory } from '../src/Modal/Modal.uni.driver';

export const modalTestkitFactory = protractorTestkitFactoryCreator(
  modalUniDriverFactory,
);

import modalSelectorLayoutDriverFactory from '../src/ModalSelectorLayout/ModalSelectorLayout.protractor.driver';

export const modalSelectorLayoutTestkitFactory = protractorTestkitFactoryCreator(
  modalSelectorLayoutDriverFactory,
);

import multiSelectDriverFactory from '../src/MultiSelect/MultiSelect.protractor.driver';

export const multiSelectTestkitFactory = protractorTestkitFactoryCreator(
  multiSelectDriverFactory,
);

import multiSelectCheckboxDriverFactory from '../src/MultiSelectCheckbox/MultiSelectCheckbox.protractor.driver';

export const multiSelectCheckboxTestkitFactory = protractorTestkitFactoryCreator(
  multiSelectCheckboxDriverFactory,
);

import multiSelectCompositeDriverFactory from '../src/MultiSelectComposite/MultiSelectComposite.protractor.driver';

export const multiSelectCompositeTestkitFactory = protractorTestkitFactoryCreator(
  multiSelectCompositeDriverFactory,
);

import { noBorderInputDriverFactory } from '../src/NoBorderInput/NoBorderInput.protractor.driver';

export const noBorderInputTestkitFactory = protractorTestkitFactoryCreator(
  noBorderInputDriverFactory,
);

import { notificationUniDriverFactory } from '../src/Notification/Notification.uni.driver';

export const notificationTestkitFactory = protractorUniTestkitFactoryCreator(
  notificationUniDriverFactory,
);

import { numberInputDriverFactory } from '../src/NumberInput/NumberInput.uni.driver';

export const numberInputTestkitFactory = protractorUniTestkitFactoryCreator(
  numberInputDriverFactory,
);

import pageDriverFactory from '../src/Page/Page.protractor.driver';

export const pageTestkitFactory = protractorTestkitFactoryCreator(
  pageDriverFactory,
);

import pageHeaderDriverFactory from '../src/PageHeader/PageHeader.protractor.driver';

export const pageHeaderTestkitFactory = protractorTestkitFactoryCreator(
  pageHeaderDriverFactory,
);

import popoverDriverFactory from '../src/Popover/Popover.protractor.driver';

export const popoverTestkitFactory = protractorTestkitFactoryCreator(
  popoverDriverFactory,
);

import popoverMenuDriverFactory from '../src/PopoverMenu/PopoverMenu.protractor.driver';

export const popoverMenuTestkitFactory = protractorTestkitFactoryCreator(
  popoverMenuDriverFactory,
);

import { proportionDriverFactory } from '../src/Proportion/Proportion.uni.driver';

export const proportionTestkitFactory = protractorUniTestkitFactoryCreator(
  proportionDriverFactory,
);

import radioGroupDriverFactory from '../src/RadioGroup/RadioGroup.protractor.driver';

export const radioGroupTestkitFactory = protractorTestkitFactoryCreator(
  radioGroupDriverFactory,
);

import rangeDriverFactory from '../src/Range/Range.protractor.driver';

export const rangeTestkitFactory = protractorTestkitFactoryCreator(
  rangeDriverFactory,
);

import { richTextInputAreaDriverFactory } from '../src/RichTextInputArea/RichTextInputArea.uni.driver';

export const richTextInputAreaTestkitFactory = protractorUniTestkitFactoryCreator(
  richTextInputAreaDriverFactory,
);

import searchDriverFactory from '../src/Search/Search.protractor.driver';

export const searchTestkitFactory = protractorTestkitFactoryCreator(
  searchDriverFactory,
);

import sectionHelperDriverFactory from '../src/SectionHelper/SectionHelper.protractor.driver';

export const sectionHelperTestkitFactory = protractorTestkitFactoryCreator(
  sectionHelperDriverFactory,
);

import { segmentedToggleDriverFactory } from '../src/SegmentedToggle/SegmentedToggle.uni.driver';

export const segmentedToggleTestkitFactory = protractorUniTestkitFactoryCreator(
  segmentedToggleDriverFactory,
);

import { sidebarDriverFactory } from '../src/Sidebar/Sidebar.uni.driver';

export const sidebarTestkitFactory = protractorUniTestkitFactoryCreator(
  sidebarDriverFactory,
);

import sidebarSectionTitleDriverFactory from '../src/SidebarSectionTitle/SidebarSectionTitle.uni.driver';

export const sidebarSectionTitleTestkitFactory = protractorUniTestkitFactoryCreator(
  sidebarSectionTitleDriverFactory,
);

import sliderDriverFactory from '../src/Slider/Slider.protractor.driver';

export const sliderTestkitFactory = protractorTestkitFactoryCreator(
  sliderDriverFactory,
);

import { socialPreviewDriverFactory } from '../src/SocialPreview/SocialPreview.uni.driver';

export const socialPreviewTestkitFactory = protractorUniTestkitFactoryCreator(
  socialPreviewDriverFactory,
);

import statsWidgetDriverFactory from '../src/StatsWidget/StatsWidget.protractor.driver';

export const statsWidgetTestkitFactory = protractorTestkitFactoryCreator(
  statsWidgetDriverFactory,
);

import { stepperDriverFactory } from '../src/Stepper/Stepper.uni.driver';

export const stepperTestkitFactory = protractorUniTestkitFactoryCreator(
  stepperDriverFactory,
);

import { swatchesDriverFactory } from '../src/Swatches/Swatches.uni.driver';

export const swatchesTestkitFactory = protractorUniTestkitFactoryCreator(
  swatchesDriverFactory,
);

import tableDriverFactory from '../src/Table/Table.protractor.driver';

export const tableTestkitFactory = protractorTestkitFactoryCreator(
  tableDriverFactory,
);

import tableActionCellDriverFactory from '../src/TableActionCell/TableActionCell.protractor.driver';

export const tableActionCellTestkitFactory = protractorTestkitFactoryCreator(
  tableActionCellDriverFactory,
);

import tabsDriverFactory from '../src/Tabs/Tabs.protractor.driver';

export const tabsTestkitFactory = protractorTestkitFactoryCreator(
  tabsDriverFactory,
);

import tagDriverFactory from '../src/Tag/Tag.protractor.driver';

export const tagTestkitFactory = protractorTestkitFactoryCreator(
  tagDriverFactory,
);

import textDriverFactory from '../src/Text/Text.protractor.driver';

export const textTestkitFactory = protractorTestkitFactoryCreator(
  textDriverFactory,
);

import { textButtonDriverFactory } from '../src/TextButton/TextButton.uni.driver';

export const textButtonTestkitFactory = protractorUniTestkitFactoryCreator(
  textButtonDriverFactory,
);

import { thumbnailDriverFactory } from '../src/Thumbnail/Thumbnail.uni.driver';

export const thumbnailTestkitFactory = protractorUniTestkitFactoryCreator(
  thumbnailDriverFactory,
);

import { timeInputUniDriverFactory } from '../src/TimeInput/TimeInput.uni.driver';

export const timeInputTestkitFactory = protractorTestkitFactoryCreator(
  timeInputUniDriverFactory,
);

import toggleSwitchDriverFactory from '../src/ToggleSwitch/ToggleSwitch.protractor.driver';

export const toggleSwitchTestkitFactory = protractorTestkitFactoryCreator(
  toggleSwitchDriverFactory,
);

import sidebarSectionItemDriverFactory from '../src/SidebarSectionItem/SidebarSectionItem.uni.driver';

export const sidebarSectionItemTestkitFactory = protractorUniTestkitFactoryCreator(
  sidebarSectionItemDriverFactory,
);

import sidebarDividerDriverFactory from '../src/SidebarDivider/SidebarDivider.uni.driver';

export const sidebarDividerTestkitFactory = protractorUniTestkitFactoryCreator(
  sidebarDividerDriverFactory,
);

import sidebarHeaderDriverFactory from '../src/SidebarHeader/SidebarHeader.uni.driver';

export const sidebarHeaderTestkitFactory = protractorUniTestkitFactoryCreator(
  sidebarHeaderDriverFactory,
);

import { modalPreviewLayoutDriverFactory } from '../src/ModalPreviewLayout/ModalPreviewLayout.uni.driver';

export const modalPreviewLayoutTestkitFactory = protractorUniTestkitFactoryCreator(
  modalPreviewLayoutDriverFactory,
);

import statisticsWidgetDriverFactory from '../src/StatisticsWidget/StatisticsWidget.uni.driver';

export const statisticsWidgetTestkitFactory = protractorUniTestkitFactoryCreator(
  statisticsWidgetDriverFactory,
);

import fillPreviewDriverFactory from '../src/FillPreview/FillPreview.uni.driver';

export const fillPreviewTestkitFactory = protractorUniTestkitFactoryCreator(
  fillPreviewDriverFactory,
import fillButtonDriverFactory from '../src/FillButton/FillButton.uni.driver';

export const fillButtonTestkitFactory = protractorUniTestkitFactoryCreator(
  fillButtonDriverFactory,
);

import labelledElementDriverFactory from '../src/LabelledElement/LabelledElement.uni.driver';

export const labelledElementTestkitFactory = protractorUniTestkitFactoryCreator(
  labelledElementDriverFactory,
);

import sideMenuDrillDriverFactory from '../src/Deprecated/SideMenu/DrillView/DrillView.protractor.driver';

export const drillViewTestkitFactory = protractorTestkitFactoryCreator(
  sideMenuDrillDriverFactory,
);

import { headerUniDriverFactory } from '../src/Card/Header/Header.uni.driver';

export const cardHeaderTestkitFactory = protractorTestkitFactoryCreator(
  headerUniDriverFactory,
);

import richTextAreaDriverFactory from '../src/Deprecated/RichTextArea/RichTextArea.protractor.driver';

export const richTextAreaTestkitFactory = protractorTestkitFactoryCreator(
  richTextAreaDriverFactory,
);

import richTextAreaCompositeDriverFactory from '../src/Deprecated/RichTextAreaComposite/RichTextAreaComposite.driver';

export const richTextAreaCompositeTestkitFactory = protractorTestkitFactoryCreator(
  richTextAreaCompositeDriverFactory,
);

import { sideMenuUniDriverFactory } from '../src/Deprecated/SideMenu/core/SideMenu.uni.driver';

export const sideMenuTestkitFactory = protractorTestkitFactoryCreator(
  sideMenuUniDriverFactory,
);

import { editableRowUniDriverFactory } from '../src/EditableSelector/EditableRow/EditableRow.uni.driver';

export const editableRowTestkitFactory = protractorTestkitFactoryCreator(
  editableRowUniDriverFactory,
);

import fieldLabelAttributesDriverFactory from '../src/FieldLabelAttributes/FieldLabelAttributes.driver';

export const fieldLabelAttributesTestkitFactory = protractorTestkitFactoryCreator(
  fieldLabelAttributesDriverFactory,
);

import fieldWithSelectionCompositeDriverFactory from '../src/Composite/FieldWithSelectionComposite/FieldWithSelectionComposite.protractor.driver';

export const fieldWithSelectionCompositeTestkitFactory = protractorTestkitFactoryCreator(
  fieldWithSelectionCompositeDriverFactory,
);

import radioButtonDriverFactory from '../src/RadioGroup/RadioButton/RadioButton.protractor.driver';

export const radioButtonTestkitFactory = protractorTestkitFactoryCreator(
  radioButtonDriverFactory,
);

import { messageBoxMarketerialLayoutUniDriverFactory } from '../src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.uni.driver';

export const messageBoxMarketerialLayoutTestkitFactory = protractorTestkitFactoryCreator(
  messageBoxMarketerialLayoutUniDriverFactory,
);

import messageBoxFunctionalLayoutDriverFactory from '../src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.protractor.driver';

export const messageBoxFunctionalLayoutTestkitFactory = protractorTestkitFactoryCreator(
  messageBoxFunctionalLayoutDriverFactory,
);

import { cardSubheaderDriverFactory } from '../src/Card/Subheader/Subheader.uni.driver';

export const subheaderTestkitFactory = protractorUniTestkitFactoryCreator(
  cardSubheaderDriverFactory,
);

