/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/testkits/puppeteer-typescript.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
export const tooltipTestkitFactory: any;
export const accordionTestkitFactory: any;
export const addItemTestkitFactory: any;
export const autoCompleteTestkitFactory: any;
export const avatarTestkitFactory: any;
export const badgeTestkitFactory: any;
export const boxTestkitFactory: any;
export const breadcrumbsTestkitFactory: any;
export const buttonTestkitFactory: any;
export const calendarTestkitFactory: any;
export const calendarPanelTestkitFactory: any;
export const calendarPanelFooterTestkitFactory: any;
export const cardGalleryItemTestkitFactory: any;
export const checkboxTestkitFactory: any;
export const closeButtonTestkitFactory: any;
export const colorInputTestkitFactory: any;
export const contactItemBuilderTestkitFactory: any;
export const dataTableTestkitFactory: any;
export const dateInputTestkitFactory: any;
export const dropdownTestkitFactory: any;
export const dropdownBaseTestkitFactory: any;
export const dropdownLayoutTestkitFactory: any;
export const editableSelectorTestkitFactory: any;
export const editableTitleTestkitFactory: any;
export const emptyStateTestkitFactory: any;
export const errorIndicatorTestkitFactory: any;
export const floatingNotificationTestkitFactory: any;
export const formFieldTestkitFactory: any;
export const genericModalLayoutTestkitFactory: any;
export const googlePreviewTestkitFactory: any;
export const headingTestkitFactory: any;
export const iconButtonTestkitFactory: any;
export const imageViewerTestkitFactory: any;
export const inputTestkitFactory: any;
export const inputAreaTestkitFactory: any;
export const inputWithOptionsTestkitFactory: any;
export const loaderTestkitFactory: any;
export const modalTestkitFactory: any;
export const multiSelectTestkitFactory: any;
export const multiSelectCheckboxTestkitFactory: any;
export const noBorderInputTestkitFactory: any;
export const notificationTestkitFactory: any;
export const numberInputTestkitFactory: any;
export const proportionTestkitFactory: any;
export const richTextInputAreaTestkitFactory: any;
export const searchTestkitFactory: any;
export const sectionHelperTestkitFactory: any;
export const segmentedToggleTestkitFactory: any;
export const sliderTestkitFactory: any;
export const socialPreviewTestkitFactory: any;
export const statsWidgetTestkitFactory: any;
export const stepperTestkitFactory: any;
export const tableTestkitFactory: any;
export const tabsTestkitFactory: any;
export const tagTestkitFactory: any;
export const textTestkitFactory: any;
export const textButtonTestkitFactory: any;
export const thumbnailTestkitFactory: any;
export const timeInputTestkitFactory: any;
export const drillViewTestkitFactory: any;
export const cardHeaderTestkitFactory: any;
export const sideMenuTestkitFactory: any;
export const editableRowTestkitFactory: any;
export const messageBoxMarketerialLayoutTestkitFactory: any;
export const messageBoxFunctionalLayoutTestkitFactory: any;

